import React, { useState, useEffect, useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { generateVoxelScene } from '../services/gemini';
import {
    getAvatarById,
    saveAvatar,
    createInitialStats,
    getInitialGrowthStats,
    addExperience,
    type AvatarData,
    type MoodState
} from '../utils/storage';
import { DUMMY_VOXEL_DOG_CODE } from '../data/dummyVoxelDog';
import springBg from '../assets/backgrounds/background_spring.png';
import summerBg from '../assets/backgrounds/background_summer.png';
import autumnBg from '../assets/backgrounds/background_autumn.png';
import winterBg from '../assets/backgrounds/background_winter.png';
import forestBg from '../assets/backgrounds/background_forest.png';
import seaBg from '../assets/backgrounds/background_sea.png';

// Simple Particle Interface
interface Particle {
    id: number;
    x: number;
    y: number;
    emoji: string;
}

// Helper for Growth Stage
const getGrowthStage = (level: number = 1) => {
    if (level < 5) return { name: 'Baby', scale: 0.8, emoji: '👶' };
    if (level < 10) return { name: 'Teen', scale: 1.0, emoji: '🧑' };
    return { name: 'Adult', scale: 1.2, emoji: '🦸' };
};

const AvatarView: React.FC = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const iframeRef = useRef<HTMLIFrameElement>(null);

    // Params from state
    const { image, style = 'voxel', name, avatarId } = (location.state as { image?: string, style?: string, name?: string, avatarId?: string }) || {};

    // Persist current avatar ID for game resilience
    useEffect(() => {
        if (avatarId) {
            localStorage.setItem('currentAvatarId', avatarId);
        }
    }, [avatarId]);

    const [avatar, setAvatar] = useState<AvatarData | null>(null);
    const [status, setStatus] = useState<'idle' | 'generating' | 'error'>('idle');
    const [thinkingText, setThinkingText] = useState<string | null>(null);
    const [errorMsg, setErrorMsg] = useState('');
    const [particles, setParticles] = useState<Particle[]>([]);

    const hasAutoGenerated = useRef(false);

    // --- Particle System ---
    const particleIdCounter = useRef(0);

    const addParticles = (x: number, y: number, emoji: string) => {
        const newParticles: Particle[] = [];
        for (let i = 0; i < 5; i++) {
            particleIdCounter.current += 1;
            newParticles.push({
                id: Date.now() + particleIdCounter.current,
                x: x + (Math.random() * 60 - 30),
                y: y + (Math.random() * 60 - 30),
                emoji
            });
        }
        setParticles(prev => [...prev, ...newParticles]);
        // Cleanup after animation
        setTimeout(() => {
            setParticles(prev => prev.filter(p => p.id < Date.now()));
        }, 1000);
    };

    // Load or Generate Avatar
    useEffect(() => {
        let targetId = avatarId;

        // Only fallback to local storage if NO new creation params are present
        if (!targetId && !image) {
            const lastId = localStorage.getItem('lastActiveAvatarId');
            if (lastId) {
                targetId = lastId;
            }
        }

        if (targetId) {
            const saved = getAvatarById(targetId);
            if (saved) {
                // Migration check: ensure growth stats exist
                if (saved.level === undefined) {
                    Object.assign(saved, getInitialGrowthStats());
                }
                // Migration check: ensure apples exist
                if (saved.apples === undefined) {
                    saved.apples = 5;
                    // We don't need to save explicitly here strictly, but it's good practice updates are persisted
                    // However, setAvatar(saved) + lazy save is fine, or explicit save:
                    saveAvatar(saved);
                }

                setAvatar(saved);
                // Refresh the active ID
                localStorage.setItem('lastActiveAvatarId', saved.id);
                return;
            }
        }

        // Only generate if we have image/style but NO existing avatar loaded (and haven't tried yet)
        if (image && style && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            handleGenerateVoxel();
        }
    }, [avatarId, image, style]);

    // Scenario 1: Daily Health Deduction
    useEffect(() => {
        if (!avatar) return;

        const now = Date.now();
        const oneDay = 24 * 60 * 60 * 1000;
        const lastUpdate = avatar.lastDailyUpdate || avatar.createdAt;
        const lastPlay = avatar.lastPlayedAt || avatar.createdAt;

        // Check if 24 hours have passed since the last deduction check
        if (now - lastUpdate >= oneDay) {
            let updatedHealth = avatar.stats.health;
            let updatedLastDailyUpdate = now;

            // If they haven't played for more than 24 hours, deduct 2 HP
            if (now - lastPlay >= oneDay) {
                updatedHealth = Math.max(0, avatar.stats.health - 2);
                console.log(`Daily penalty: -2 HP. New Health: ${updatedHealth}`);
            }

            const updatedAvatar: AvatarData = {
                ...avatar,
                stats: {
                    ...avatar.stats,
                    health: updatedHealth
                },
                lastDailyUpdate: updatedLastDailyUpdate,
                isDead: updatedHealth <= 0
            };

            setAvatar(updatedAvatar);
            saveAvatar(updatedAvatar);

            if (updatedHealth <= 0) {
                navigate('/select-avatar', { state: { deathAlert: avatar.name } });
            }
        }
    }, [avatar?.id, navigate]); // Only run when avatar loads or changes identity

    const handleGenerateVoxel = async () => {
        if (!image || !style) return;
        setStatus('generating');
        setErrorMsg('');

        try {
            const code = await generateVoxelScene(image, (thought) => {
                setThinkingText(thought);
            });

            const newAvatar: AvatarData = {
                id: Math.random().toString(36).substr(2, 9),
                name: name || 'Buddy',
                image,
                style: style || 'voxel',
                voxelCode: code,
                stats: createInitialStats(),
                ...getInitialGrowthStats(),
                currentMoodState: 'happy',
                createdAt: Date.now()
            };

            setAvatar(newAvatar);
            saveAvatar(newAvatar);
            localStorage.setItem('lastActiveAvatarId', newAvatar.id);
            setStatus('idle');
            setThinkingText(null);
        } catch (err: any) {
            console.error(err);
            setStatus('error');
            setErrorMsg(err.message || 'Failed to generate 3D avatar.');
            hasAutoGenerated.current = false; // Allow retry on error
        }
    };

    const handleLoadDummy = () => {
        const dummyAvatar: AvatarData = {
            id: 'dummy-dog',
            name: 'Buddy',
            image: '',
            style: 'voxel',
            voxelCode: DUMMY_VOXEL_DOG_CODE,
            stats: createInitialStats(),
            ...getInitialGrowthStats(),
            currentMoodState: 'happy',
            createdAt: Date.now()
        };
        setAvatar(dummyAvatar);
    };

    const handleAction = (action: string, e: React.MouseEvent) => {
        if (!avatar) return;

        // Visual Feedback (Particles)
        const rect = (e.target as HTMLElement).getBoundingClientRect();
        const centerX = rect.left + rect.width / 2;
        const centerY = rect.top + rect.height / 2;

        const newStats = { ...avatar.stats };
        let updatedAvatar = { ...avatar };
        let newMood: MoodState | undefined;
        let particleEmoji = '✨';
        let xpReward = 0;
        let success = false;

        switch (action) {
            case 'feed':
                // Check Inventory
                if ((avatar.apples || 0) > 0) {
                    updatedAvatar.apples = (avatar.apples || 0) - 1;
                    success = true;

                    // Heal if needed
                    if (newStats.health < 5) {
                        newStats.health = Math.min(5, newStats.health + 1);
                        newMood = 'happy';
                    }
                    console.log('Feeding avatar:', avatar.apples);
                    // Always happy to eat
                    particleEmoji = '🍎';
                    xpReward = 30;
                    addParticles(centerX, centerY, particleEmoji);
                } else {
                    addParticles(centerX, centerY, '🚫'); // No food
                    // Maybe show a toast message?
                }
                break;
            case 'rest':
                // Always allow rest, just cap stats
                success = true;
                if (newStats.mana < 5) {
                    newStats.mana = Math.min(5, newStats.mana + 1);
                }
                newMood = 'sleepy';
                particleEmoji = '💤';
                xpReward = 10; // Bump up rest reward since it's an action
                addParticles(centerX, centerY, particleEmoji);
                break;
            case 'train':
                // Only train if Mana > 0
                if (newStats.mana > 0) {
                    newStats.mana = Math.max(0, newStats.mana - 1);
                    newStats.health = Math.min(5, newStats.health + 1);
                    success = true;
                    newMood = 'excited';
                    particleEmoji = '💪';
                    xpReward = 10;
                    addParticles(centerX, centerY, particleEmoji);
                } else {
                    addParticles(centerX, centerY, '🚫');
                }
                break;
        }

        // Apply stat updates
        updatedAvatar.stats = newStats;
        if (newMood) updatedAvatar.currentMoodState = newMood;

        // Apply XP Logic if reward
        if (xpReward > 0) {
            saveAvatar(updatedAvatar); // Save updates (inventory/stats) before adding XP
            const xpResult = addExperience(updatedAvatar.id, xpReward);
            if (xpResult.avatar) {
                updatedAvatar = xpResult.avatar;
                // TODO: Show Level Up Animation if xpResult.leveledUp
                if (xpResult.leveledUp) {
                    addParticles(centerX, centerY, '🎉');
                    addParticles(centerX, centerY, '🆙');
                }
            }
        } else if (success) {
            saveAvatar(updatedAvatar);
        }

        setAvatar(updatedAvatar);

        // Always notify iframe of the action's associated mood to trigger animation if successful
        // We map action -> mood for animation purposes
        let animationMood = '';
        if (action === 'feed') animationMood = 'happy';
        if (action === 'rest') animationMood = 'sleepy';
        if (action === 'train') animationMood = 'excited';

        if (success && animationMood && iframeRef.current?.contentWindow) {
            iframeRef.current.contentWindow.postMessage({ type: 'CHANGE_MOOD', mood: animationMood }, '*');
        }
    };


    const [season, setSeason] = useState<'spring' | 'summer' | 'autumn' | 'winter' | 'forest' | 'sea'>('spring');

    const toggleSeason = () => {
        setSeason(prev => {
            if (prev === 'spring') return 'summer';
            if (prev === 'summer') return 'autumn';
            if (prev === 'autumn') return 'winter';
            if (prev === 'winter') return 'forest';
            if (prev === 'forest') return 'sea';
            return 'spring';
        });
    };

    const getSeasonIcon = () => {
        switch (season) {
            case 'spring': return '🌸';
            case 'summer': return '☀️';
            case 'autumn': return '🍂';
            case 'winter': return '❄️';
            case 'forest': return '🌳';
            case 'sea': return '🌊';
        }
    };

    const getBackgroundStyle = () => {
        let bgImage;
        switch (season) {
            case 'spring': bgImage = springBg; break;
            case 'summer': bgImage = summerBg; break;
            case 'autumn': bgImage = autumnBg; break;
            case 'winter': bgImage = winterBg; break;
            case 'forest': bgImage = forestBg; break;
            case 'sea': bgImage = seaBg; break;
        }
        return {
            backgroundImage: `url(${bgImage})`,
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat'
        };
    };

    if (!avatar && status !== 'generating' && status !== 'error') {
        return (
            <div className="avatar-view-container" style={{ textAlign: 'center', padding: '50px' }}>
                <div className="clay-container">
                    <h2 style={{ fontSize: '2rem', marginBottom: '1rem', color: 'var(--vibrant-red)' }}>Where's your friend?</h2>
                    <p style={{ marginBottom: '2rem', fontSize: '1.2rem' }}>Let's bring them back!</p>
                    <button className="clay-button" onClick={handleLoadDummy}>Call Buddy</button>
                    <br /><br />
                    <button className="clay-button secondary" onClick={() => navigate('/')}>Make New One</button>
                </div>
            </div>
        );
    }

    const growthStage = getGrowthStage(avatar?.level);
    const xpProgress = (avatar?.xp || 0);
    const xpMax = (avatar?.maxXp || 100);

    return (
        <div className="avatar-view-fullscreen" style={{
            width: '100vw',
            height: '100vh',
            overflow: 'hidden',
            position: 'fixed',
            top: 0,
            left: 0,
            ...getBackgroundStyle(),
            display: 'flex',
            flexDirection: 'column',
            padding: '1rem',
            boxSizing: 'border-box'
        }}>

            {/* Particles Container */}
            {particles.map(p => (
                <div key={p.id} style={{
                    position: 'fixed',
                    left: p.x,
                    top: p.y,
                    fontSize: '2rem',
                    pointerEvents: 'none',
                    animation: 'float 1s ease-out forwards',
                    zIndex: 100
                }}>
                    {p.emoji}
                </div>
            ))}

            {/* Header Controls */}
            <div style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: '1rem',
                zIndex: 10,
                width: '100%'
            }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <button
                        className="clay-button secondary"
                        style={{ padding: '10px 16px', borderRadius: '50%', width: '40px', height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
                        onClick={() => navigate('/select-avatar')}
                        title="Log Out"
                    >
                        🏃
                    </button>
                    <div style={{
                        fontWeight: 900,
                        color: 'white',
                        fontSize: '1.2rem',
                        textShadow: '0 2px 4px rgba(0,0,0,0.3)',
                        background: 'rgba(0,0,0,0.2)',
                        padding: '4px 16px',
                        borderRadius: '15px',
                        backdropFilter: 'blur(5px)'
                    }}>
                        {avatar?.name || name || 'Buddy'}
                    </div>
                </div>

                <div className="level-badge" style={{
                    background: 'rgba(255,255,255,0.9)',
                    padding: '5px 15px',
                    borderRadius: '20px',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    boxShadow: '0 4px 6px rgba(0,0,0,0.1)'
                }}>
                    <div style={{ fontWeight: 800, color: '#6A5ACD', fontSize: '0.9rem' }}>
                        Lvl {avatar?.level || 1} • {growthStage.name} {growthStage.emoji}
                    </div>
                    <div style={{ width: '100%', height: '6px', background: '#eee', borderRadius: '3px', marginTop: '4px', overflow: 'hidden' }}>
                        <div style={{
                            width: `${Math.min(100, (xpProgress / xpMax) * 100)}%`,
                            height: '100%',
                            background: 'linear-gradient(90deg, #FF9F43, #FF6B6B)'
                        }}></div>
                    </div>
                </div>

                <button
                    className="clay-button secondary"
                    style={{
                        padding: '3px 3px',
                        fontSize: '1.5rem',
                        minWidth: '50px',
                        backdropFilter: 'blur(5px)',
                        borderRadius: '50%', width: '40px', height: '40px'
                    }}
                    onClick={toggleSeason}
                >
                    {getSeasonIcon()}
                </button>
            </div>

            {/* Stats Bar */}
            <div style={{
                display: 'flex',
                gap: '1rem',
                justifyContent: 'center',
                marginBottom: '1rem',
                zIndex: 10
            }}>
                <StatBadge label="❤️" value={avatar?.stats.health || 0} color="#FF6B6B" />
                <StatBadge label="✨" value={avatar?.stats.mana || 0} color="#FECA57" />
                <StatBadge label="😊" value={avatar?.stats.mood || 0} color="#54A0FF" />
            </div>

            {/* Main View Area - 3D Glass Frame */}
            <div className="animate-float" style={{
                flex: 1,
                width: '100%',
                maxWidth: '600px',
                margin: '0 auto',
                position: 'relative',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                background: 'rgba(255, 255, 255, 0.25)',
                backdropFilter: 'blur(8px)',
                borderRadius: '50px', // More rounded
                border: '4px solid rgba(255, 255, 255, 0.6)',
                boxShadow: '0 8px 32px 0 rgba(31, 38, 135, 0.15)',
                overflow: 'hidden',
                zIndex: 5
            }}>
                {status === 'generating' && (
                    <div style={{
                        position: 'absolute',
                        inset: 0,
                        background: 'rgba(255,255,255,0.9)',
                        zIndex: 20,
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'center',
                        justifyContent: 'center',
                        padding: '2rem'
                    }}>
                        <div className="clay-card" style={{ textAlign: 'center' }}>
                            <div className="animate-bounce" style={{ fontSize: '4rem', marginBottom: '1rem' }}>✨</div>
                            <h3 style={{ marginBottom: '10px', color: 'var(--vibrant-purple)' }}>Making Magic!</h3>
                            <p style={{ fontSize: '1.1rem', opacity: 0.8 }}>{thinkingText || 'Waking up your friend...'}</p>
                        </div>
                    </div>
                )}

                {status === 'error' && (
                    <div className="clay-card" style={{ padding: '20px', color: '#ff6b6b', textAlign: 'center', zIndex: 20 }}>
                        <h3 className="animate-bounce">🙈 Uh oh!</h3>
                        <p>{errorMsg}</p>
                        <button className="clay-button" onClick={handleGenerateVoxel} style={{ marginTop: '20px' }}>Try Again</button>
                    </div>
                )}

                {avatar?.voxelCode ? (
                    <div style={{
                        width: '100%',
                        height: '100%',
                        transition: 'transform 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
                        transform: `scale(${growthStage.scale})`,
                        transformOrigin: 'center bottom'
                    }}>
                        <iframe
                            ref={iframeRef}
                            title="Voxel Scene"
                            srcDoc={avatar.voxelCode}
                            style={{ width: '100%', height: '100%', border: '0' }}
                            sandbox="allow-scripts allow-same-origin"
                        />
                    </div>
                ) : (
                    avatar?.image && (
                        <div style={{ textAlign: 'center', transform: `scale(${growthStage.scale})`, transition: 'transform 0.5s' }}>
                            <img src={avatar.image} alt="Avatar" style={{ width: '80%', borderRadius: '40px', boxShadow: 'var(--clay-shadow)' }} />
                        </div>
                    )
                )}

                {/* Interaction Tooltip */}
                <div className="animate-pulse" style={{
                    position: 'absolute',
                    bottom: '25px',
                    left: '50%',
                    transform: 'translateX(-50%)',
                    background: 'rgba(255,255,255,0.85)',
                    padding: '8px 20px',
                    borderRadius: '30px',
                    fontSize: '1rem',
                    fontWeight: 700,
                    color: 'var(--vibrant-purple)',
                    backdropFilter: 'blur(10px)',
                    pointerEvents: 'none',
                    boxShadow: '0 4px 10px rgba(0,0,0,0.1)',
                    whiteSpace: 'nowrap'
                }}>
                    👆 Tap to Play!
                </div>
            </div>

            {/* Mood Text */}
            <div style={{
                textAlign: 'center',
                marginTop: '1rem',
                marginBottom: '5rem', // Space for buttons
                fontSize: '1.4rem',
                fontWeight: 800,
                color: 'white',
                textShadow: '0 2px 4px rgba(0,0,0,0.2)'
            }}>
                It's a <span style={{ color: 'white', textDecoration: 'underline decoration-wavy' }}>{avatar?.currentMoodState || 'happy'}</span> day!
            </div>

            {/* Interaction Buttons Container - Floating Dock */}
            <div style={{
                position: 'fixed',
                bottom: '30px',
                left: '50%',
                transform: 'translateX(-50%)',
                width: '90%',
                maxWidth: '500px',
                background: 'rgba(255, 255, 255, 0.9)',
                backdropFilter: 'blur(20px)',
                borderRadius: '40px',
                padding: '10px 20px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-around',
                zIndex: 100,
                boxShadow: '0 10px 30px rgba(0,0,0,0.15)',
                border: '4px solid rgba(255,255,255,0.5)'
            }}>
                {/* Feed */}
                <BubbleButton
                    icon="🍎"
                    label="Feed"
                    color="var(--vibrant-green)"
                    count={avatar?.apples || 0}
                    onClick={(e) => handleAction('feed', e)}
                />

                {/* Main Play Button - Popping out */}
                <div style={{ position: 'relative', top: '-30px' }}>
                    <button
                        className="animate-pulse"
                        onClick={(e) => {
                            e.stopPropagation();
                            console.log('Navigating to Upload Quiz with avatar:', avatar?.id);
                            navigate('/upload-quiz', { state: { avatarId: avatar?.id } });
                        }}
                        style={{
                            width: '100px',
                            height: '100px',
                            background: 'linear-gradient(135deg, #FF9F43 0%, #FF6B6B 100%)',
                            border: '6px solid white',
                            borderRadius: '35px',
                            transform: 'rotate(45deg)',
                            boxShadow: '0 15px 30px rgba(255, 107, 107, 0.4)',
                            cursor: 'pointer',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            transition: 'all 0.2s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
                        }}
                    >
                        <div style={{ transform: 'rotate(-45deg)', color: 'white', textAlign: 'center' }}>
                            <div style={{ fontSize: '2.5rem', filter: 'drop-shadow(0 2px 2px rgba(0,0,0,0.2))' }}>🎮</div>
                            <div style={{ fontSize: '0.9rem', fontWeight: 900, textTransform: 'uppercase' }}>PLAY</div>
                        </div>
                    </button>
                </div>

                {/* Rest */}
                <BubbleButton
                    icon="💤"
                    label="Rest"
                    color="var(--vibrant-blue)"
                    onClick={(e) => handleAction('rest', e)}
                />

                {/* Train - Optional 4th button or put elsewhere? Keeping as requested */}
                <BubbleButton
                    icon="💪"
                    label="Train"
                    color="var(--vibrant-orange)"
                    onClick={(e) => handleAction('train', e)}
                />
            </div>
        </div>
    );
};

// Sub-components
const StatBadge = ({ label, value, color }: { label: string, value: number, color: string }) => (
    <div style={{
        background: 'white',
        padding: '8px 16px',
        borderRadius: '20px',
        boxShadow: '0 4px 10px rgba(0,0,0,0.1)',
        fontWeight: 800,
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        color: '#555',
        fontSize: '1.2rem',
        borderBottom: `4px solid ${color}`
    }}>
        <span>{label}</span>
        <span style={{ color: color }}>{value}/5</span>
    </div>
);

const BubbleButton = ({ icon, label, onClick, color, count }: { icon: string, label: string, onClick: (e: React.MouseEvent) => void, color: string, count?: number }) => {
    return (
        <button
            onClick={onClick}
            style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                width: '60px',
                height: '60px',
                borderRadius: '20px',
                background: 'transparent',
                border: 'none',
                cursor: 'pointer',
                transition: 'transform 0.1s',
            }}
            onMouseDown={e => e.currentTarget.style.transform = 'scale(0.9)'}
            onMouseUp={e => e.currentTarget.style.transform = 'scale(1)'}
            onMouseLeave={e => e.currentTarget.style.transform = 'scale(1)'}
        >
            <div style={{
                width: '50px',
                height: '50px',
                borderRadius: '18px',
                background: color,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '1.8rem',
                boxShadow: `0 6px 0 rgba(0,0,0,0.2)`,
                color: 'white',
                border: '2px solid white'
            }}>
                {icon}
                {count !== undefined && (
                    <div style={{
                        position: 'absolute',
                        bottom: '-5px',
                        right: '-5px',
                        background: '#FF6B6B',
                        color: 'white',
                        borderRadius: '50%',
                        width: '24px',
                        height: '24px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        fontSize: '0.8rem',
                        fontWeight: 900,
                        border: '2px solid white'
                    }}>
                        {count}
                    </div>
                )}
            </div>
            <span style={{
                fontSize: '0.8rem',
                fontWeight: 800,
                color: '#555',
                marginTop: '6px'
            }}>{label}</span>
        </button>
    );
};

export default AvatarView;
